sudo: required

services:
  - docker

language: go

go: 1.6

install:
  - go get github.com/openshift/source-to-image
  - pushd ${GOPATH}/src/github.com/openshift/source-to-image
  - export PATH=$PATH:${GOPATH}/src/github.com/openshift/source-to-image/_output/local/bin/linux/amd64/
  - hack/build-go.sh
  - popd

script: 
  - make test VERSION=1.8-gradle
  - docker rm $(docker ps -aq --filter status="exited" --filter status="dead") 2>/dev/null
  - docker rmi $(docker images --filter "dangling=true" -q | sort -u) 2>/dev/null
  - docker volume rm $(docker volume ls -qf dangling=true) 2>/dev/null
  - make test VERSION=1.8-maven
